version: "3.9"

services:
  ngerp:
    container_name: "ngerp"
    image: emaco/ngerp:0.0.2
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/uploads/media/

    environment:
      - DJANGO_SETTINGS_MODULE=ngerp.settings
      - SECRET_KEY=YOUR_DOMAIN_SECRET_KEY
      - MEDIA_ROOT=/uploads/media/
      - MSSQL_HOST=host.docker.internal
      - MSSQL_NAME=ngerp
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=Mssql@12345
